name = "nickzylstra-com"
type = "webpack"
account_id = "c6a05dacf1861c2fc26e676732f094d1"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.staging]
workers_dev = true

[env.production]
routes = ["www.nickzylstra.com/*", "nickzylstra.com/*"]
zone_id = "138637767aa3d9eaaa39c3d5e2a98faa"
