version: 2
jobs:
  build-test-publish:
    docker:
      - image: circleci/node:12.15
    steps:
      - checkout
      - run: 
          name: Setup
          command: |
            npm install
            npm run build
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - run:
          name: Publish app to Workers site
          env:
            NODE_ENV: production
          command: |
            npm run build
            npx wrangler publish --env production

workflows:
  version: 2
  CICD:
    jobs:
      - build-test-publish