GET http://localhost:3000

# sample response body: API server running

###
POST http://localhost:3000/customers
content-type: application/json

{
    "name": "sample",
    "email": "bob1@business.com"
}

# sample response body: {"customerId":4}

###