@localHost = http://localhost
@localPort = 3000
@localUrl = {{localHost}}:{{localPort}}
@deployedUrl = https://www.nickzylstra.com

###

GET {{localUrl}}

# sample response body: API server running

###
GET {{deployedUrl}}

# sample response body: API server running

###
POST {{localUrl}}/api/customers
content-type: application/json

{
    "name": "sample",
    "email": "bob@business.com"
}

# sample response body: {"customerId":4}

###
POST {{deployedUrl}}/api/customers
content-type: application/json

{
    "name": "sample",
    "email": "bob@business.com"
}

# sample response body: {"customerId":4}

###